Repository high-five-ormi/Algoy-Web, pull requests merged in 2024-09, with the labels that each got.

#56 Bug/55 aop
  src/main/java/com/example/algoyweb/service/planner/PlannerService.java
  src/main/java/com/example/algoyweb/util/user/UserDeleteAspect.java
Labels: 🐞 bug

#60 Feature: AI 챗봇 기능 추가
  src/main/java/com/example/algoyweb/controller/temp/ChatBotViewController.java
  src/main/resources/application.yml
  src/main/resources/static/css/temp/chatbot.css
  src/main/resources/static/img/bot_icon.png
  src/main/resources/static/img/send_icon.png
  src/main/resources/static/js/temp/chatbot.js
  src/main/resources/templates/temp/chatbot.html
Labels: 🎨 design, ✨ feature

#61 Design: 홈화면, 로그인화면 FE 수정
  src/main/java/com/example/algoyweb/service/user/UserService.java
Labels: 🎨 design, ✨ feature

#63 Test: 테스트 코드 작성
  src/test/java/com/example/algoyweb/controller/user/UserControllerTest.java
  src/test/java/com/example/algoyweb/model/entity/user/UserTest.java
  src/test/java/com/example/algoyweb/repository/user/UserRepositoryTest.java
  src/test/java/com/example/algoyweb/service/user/UserServiceTest.java
Labels: ✅ test

#66 Bug: 컨트롤러에서 chatbot.html 경로 실수 수정
  src/main/java/com/example/algoyweb/controller/temp/ChatBotViewController.java
Labels: 🐞 bug

#68 Chore: ci/cd workflow에 AI 서버 url 환경 변수 추가
  .github/workflows/gradle.yml
Labels: 👷‍♂️ chore

#69 Chore: application.yml에 AI 서버 url 환경 변수 추가
  src/main/resources/application.yml
Labels: 👷‍♂️ chore

#71 Bug: CI 오류 해결 및 html backendUrl 받아오도록 변경
  src/main/java/com/example/algoyweb/controller/temp/ChatBotViewController.java
  src/main/resources/templates/temp/chatbot.html
  src/test/java/com/example/algoyweb/AlgoyWebApplicationTests.java
Labels: 🐞 bug

#73 test: Planner
  src/main/java/com/example/algoyweb/model/dto/planner/PlannerDto.java
  src/main/java/com/example/algoyweb/model/entity/planner/Planner.java
  src/main/java/com/example/algoyweb/repository/planner/PlannerRepository.java
  src/main/java/com/example/algoyweb/service/planner/PlannerService.java
  src/main/java/com/example/algoyweb/util/ConvertUtils.java
  src/main/resources/static/css/planner/PlannerEditForm.css
  src/main/resources/static/css/planner/PlannerMainCss.css
  src/main/resources/static/css/planner/PlannerSaveForm.css
  src/main/resources/static/js/planner/EditFormJs.js
  src/main/resources/static/js/planner/PlannerMainJs.js
  src/main/resources/static/js/planner/SaveFormJs.js
  src/main/resources/templates/planner/EditForm.html
  src/main/resources/templates/planner/PlannerMain.html
  src/main/resources/templates/planner/SaveForm.html
  src/test/java/com/example/service/planner/PlannerServiceTest.java
Labels: ⚒️ refactor, ✅ test

#74 Bug: AI_IP 환경 변수 추가 후 배포 문제 수정
  .github/workflows/gradle.yml
Labels: 🐞 bug

#75 Bug: AI_IP 환경 변수 추가 후 배포 문제 수정
  .github/workflows/gradle.yml
Labels: 🐞 bug

#76 Bug: AI_IP 환경 변수 추가 후 배포 문제 수정
  src/main/resources/application.yml
Labels: 🐞 bug

#77 Bug: AI_IP 환경 변수 추가 후 배포 문제 수정
  .github/workflows/gradle.yml
Labels: 🐞 bug

#78 Bug: IP 환경 변수 추가
  .github/workflows/gradle.yml
Labels: 🐞 bug

#79 Bug: 챗봇 연결 안됨
  src/main/resources/application.yml
Labels: 🐞 bug

#80 Bug: Bad Gateway 해결
  src/main/resources/application.yml
Labels: 🐞 bug

#81 Bug: 챗봇 연결 안됨
  src/main/resources/application.yml
Labels: 🐞 bug

#82 Bug: CI/CD 원상 복구
  .github/workflows/gradle.yml
Labels: 🐞 bug

#83 Chore: ci/cd workflows 구조 변경
  .github/workflows/gradle.yml
Labels: 👷‍♂️ chore

#84 Bug: gradle.yml 수정
  .github/workflows/gradle.yml
Labels: 🐞 bug

#85 Feat: http로 solvedAC 연동
  src/main/java/com/example/algoyweb/controller/allen/AllenController.java
  src/main/java/com/example/algoyweb/service/allen/AllenService.java
  src/main/java/com/example/algoyweb/service/allen/HttpURLConnectionEx.java
Labels: ✨ feature

#86 Feature/62 회원정보 수정
  src/main/java/com/example/algoyweb/config/SecurityConfig.java
  src/main/java/com/example/algoyweb/controller/HomeController.java
  src/main/java/com/example/algoyweb/controller/user/MyPageController.java
  src/main/java/com/example/algoyweb/controller/user/UserController.java
  src/main/java/com/example/algoyweb/model/dto/user/UserDto.java
  src/main/java/com/example/algoyweb/model/entity/user/User.java
  src/main/java/com/example/algoyweb/service/user/UserService.java
  src/main/resources/static/css/fragments/header.css
  src/main/resources/static/css/fragments/modal.css
  src/main/resources/static/css/home/home.css
  src/main/resources/static/css/mypage/editUser.css
  src/main/resources/static/css/user/login.css
  src/main/resources/static/js/fragments/modal.js
  src/main/resources/static/js/home.js
  src/main/resources/static/js/mypage/userDelete.js
  src/main/resources/static/js/mypage/userEdit.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/modal.html
  src/main/resources/templates/home.html
  src/main/resources/templates/mypage/userDelete.html
  src/main/resources/templates/mypage/userEdit.html
  src/main/resources/templates/user/login.html
Labels: 🎨 design, ✨ feature

#87 Bug: 챗봇 연결 안됨
  src/main/resources/templates/temp/chatbot.html
Labels: 🐞 bug

#90 refactoring: Planner
  src/main/java/com/example/algoyweb/controller/planner/PlannerController.java
  src/main/java/com/example/algoyweb/service/planner/PlannerService.java
  src/main/java/com/example/algoyweb/util/user/UserDeleteAspect.java
  src/main/resources/static/css/planner/PlannerEditForm.css
  src/main/resources/static/css/planner/PlannerMainCss.css
  src/main/resources/static/css/planner/PlannerSaveForm.css
  src/main/resources/static/js/planner/EditFormJs.js
  src/main/resources/static/js/planner/PlannerMainJs.js
  src/main/resources/static/js/planner/SaveFormJs.js
  src/main/resources/templates/planner/EditForm.html
  src/main/resources/templates/planner/PlannerMain.html
  src/main/resources/templates/planner/SaveForm.html
  src/test/java/com/example/algoyweb/service/planner/PlannerServiceTest.java
Labels: ⚒️ refactor

#91 Refactor: yml파일 update로 변경
  src/main/resources/application.yml
Labels: ⚒️ refactor

#92 Feature: 비밀번호 찾기
  src/main/java/com/example/algoyweb/config/SecurityConfig.java
  src/main/java/com/example/algoyweb/controller/user/UserController.java
  src/main/java/com/example/algoyweb/model/entity/user/User.java
  src/main/java/com/example/algoyweb/repository/user/UserRepository.java
  src/main/java/com/example/algoyweb/service/user/UserService.java
  src/main/resources/static/css/password/find.css
  src/main/resources/static/css/password/reset.css
  src/main/resources/static/css/signup/signup.css
  src/main/resources/static/js/signup/signup.js
  src/main/resources/templates/mypage/editUser.html
  src/main/resources/templates/password/find-password.html
  src/main/resources/templates/password/reset-password.html
  src/main/resources/templates/signup/signup.html
  src/main/resources/templates/user/login.html
Labels: ✨ feature

#93 Bug: 챗봇 연결 안됨
  src/main/resources/templates/temp/chatbot.html
Labels: 🐞 bug

#94 Refactor: config에 allen 추가
  src/main/java/com/example/algoyweb/config/SecurityConfig.java
Labels: ⚒️ refactor

#95 Feat: solvedac 연동 수정
  src/main/java/com/example/algoyweb/controller/allen/AllenController.java
  src/main/java/com/example/algoyweb/service/allen/AllenService.java
  src/main/resources/application.yml
Labels: ✨ feature

#96 Feature/35 오답노트
  src/main/java/com/example/algoyweb/controller/WrongAnswerNote/ImageController.java
  src/main/java/com/example/algoyweb/controller/WrongAnswerNote/WrongAnswerNoteRestController.java
  src/main/java/com/example/algoyweb/controller/WrongAnswerNote/WrongAnswerNoteThymeleafController.java
  src/main/java/com/example/algoyweb/exception/ImageNotFoundException.java
  src/main/java/com/example/algoyweb/model/dto/WrongAnswerNote/ImageDTO.java
  src/main/java/com/example/algoyweb/model/dto/WrongAnswerNote/WrongAnswerNoteDTO.java
  src/main/java/com/example/algoyweb/model/entity/WrongAnswerNote/Image.java
  src/main/java/com/example/algoyweb/model/entity/WrongAnswerNote/WrongAnswerNote.java
  src/main/java/com/example/algoyweb/repository/WrongAnswerNote/ImageRepository.java
  src/main/java/com/example/algoyweb/service/WrongAnswerNote/ImageService.java
  src/main/java/com/example/algoyweb/service/WrongAnswerNote/WrongAnswerNoteService.java
  src/main/java/com/example/algoyweb/util/WrongAnswerNote/ImageConvertUtil.java
  src/main/java/com/example/algoyweb/util/WrongAnswerNote/WrongAnswerNoteConvertUtil.java
  src/main/resources/static/css/wronganswernote/create-wrong-answer-note.css
  src/main/resources/static/css/wronganswernote/edit-wrong-answer-note.css
  src/main/resources/static/css/wronganswernote/list-wrong-answer-note.css
  src/main/resources/static/css/wronganswernote/view-wrong-answer-note.css
  src/main/resources/static/js/wronganswernote/create.js
  src/main/resources/static/js/wronganswernote/edit.js
  src/main/resources/static/js/wronganswernote/list.js
  src/main/resources/static/js/wronganswernote/view.js
  src/main/resources/templates/wronganswernote/create-wrong-answer-note.html
  src/main/resources/templates/wronganswernote/edit-wrong-answer-note.html
  src/main/resources/templates/wronganswernote/list-wrong-answer-notes.html
  src/main/resources/templates/wronganswernote/view-wrong-answer-note.html
Labels: 🎨 design, ✨ feature

#98 feat: Planner search
  src/main/java/com/example/algoyweb/controller/planner/PlannerController.java
  src/main/java/com/example/algoyweb/repository/planner/PlannerRepository.java
  src/main/java/com/example/algoyweb/service/planner/PlannerService.java
  src/main/resources/static/css/planner/PlannerMainCss.css
  src/main/resources/static/js/planner/EditFormJs.js
  src/main/resources/static/js/planner/PlannerMainJs.js
  src/main/resources/static/js/planner/SaveFormJs.js
  src/main/resources/templates/planner/PlannerMain.html
Labels: ✨ feature, ⚒️ refactor

#101 Feat: solvedAC API로 유저가 푼 100문제 가져오기
  build.gradle
  src/main/java/com/example/algoyweb/controller/allen/AllenController.java
  src/main/java/com/example/algoyweb/model/dto/allen/SolvedACResponse.java
  src/main/java/com/example/algoyweb/service/allen/AllenService.java
Labels: ✨ feature

#104 Feat: user정보기반으로 allen에게 문제추천받는 기능
  src/main/java/com/example/algoyweb/controller/allen/AllenController.java
  src/main/java/com/example/algoyweb/service/allen/AllenService.java
  src/main/resources/application.yml
Labels: ✨ feature

#107 Refactor: 회원 탈퇴, CSS 수정
  src/main/java/com/example/algoyweb/model/entity/user/User.java
  src/main/resources/static/css/mypage/deleteUser.css
  src/main/resources/templates/mypage/userDelete.html
  src/main/resources/templates/mypage/userEdit.html
  src/main/resources/templates/signup/signup.html
Labels: ⚒️ refactor

#108 Enhancement: 챗봇 다른 페이지에 붙일 수 있게 변경
  src/main/java/com/example/algoyweb/controller/temp/ChatBotViewController.java
  src/main/resources/static/css/fragments/chatbot.css
  src/main/resources/static/js/fragments/chatbot.js
  src/main/resources/static/js/temp/chatbot.js
  src/main/resources/templates/fragments/chatbot.html
  src/main/resources/templates/temp/chatbot-demo.html
  src/main/resources/templates/temp/chatbot.html
Labels: 🎨 design, 📚 documentation, 💪 enhancement, ⚒️ refactor

#112 Design: 문제 추천받기 디자인 구현
  src/main/java/com/example/algoyweb/controller/allen/AllenController.java
  src/main/resources/static/css/allen/allenpick.css
  src/main/resources/templates/home.html
Labels: 🎨 design

#113 Chore: ci/cd workflows 구조 변경
  .github/workflows/gradle.yml
Labels: 👷‍♂️ chore

#115 Refactor: 환경 변수에 맞게 코드 변경
  src/main/resources/application.yml
  src/main/resources/templates/fragments/chatbot.html
  src/main/resources/templates/temp/chatbot-demo.html
Labels: ⚒️ refactor

#116 Feature: 홈 API 플래너 연동
  src/main/resources/static/css/home/calendar.css
  src/main/resources/static/css/home/home.css
  src/main/resources/static/js/graph/calendar.global.js
  src/main/resources/static/js/graph/graph.js
  src/main/resources/templates/home.html
Labels: ✨ feature

#117 Remove: 불필요 파일 삭제
  src/main/resources/static/js/calendar/add-event.js
Labels: ⚒️ refactor

#120 Bug: 챗봇의 환경 변수 url 전달이 안되는 문제 해결
  src/main/resources/templates/fragments/chatbot.html
  src/main/resources/templates/temp/chatbot-demo.html
Labels: 🐞 bug

#122 Remove: 불필요 파일 삭제
  src/main/resources/templates/mypage/mypage.html
Labels: ⚒️ refactor

#124 Feature: 회원 권한 관리
  src/main/java/com/example/algoyweb/config/SecurityConfig.java
  src/main/java/com/example/algoyweb/controller/user/AdminController.java
  src/main/java/com/example/algoyweb/model/entity/user/Role.java
  src/main/java/com/example/algoyweb/model/entity/user/User.java
  src/main/java/com/example/algoyweb/repository/user/UserRepository.java
  src/main/java/com/example/algoyweb/service/user/UserService.java
  src/main/resources/static/css/user/admin.css
  src/main/resources/templates/user/admin.html
Labels: ✨ feature

#125 Feat: 앨런 답변 파싱 및 변환
  src/main/java/com/example/algoyweb/controller/allen/AllenController.java
  src/main/java/com/example/algoyweb/service/allen/AllenService.java
Labels: ✨ feature

#129 Design/128 home 디자인 변경
  src/main/resources/static/css/fragments/header.css
  src/main/resources/static/css/home/calendar.css
  src/main/resources/static/css/home/home.css
  src/main/resources/static/js/graph/graph.js
  src/main/resources/templates/home.html
Labels: 🎨 design

#131 Design: 홈 화면에 챗봇 프래그먼트 붙이기
  src/main/java/com/example/algoyweb/controller/HomeController.java
  src/main/resources/templates/home.html
  src/main/resources/templates/temp/chatbot-demo.html
Labels: 🎨 design

#132 Design: 오답노트 화면에 챗봇 프래그먼트 붙이기
  src/main/java/com/example/algoyweb/controller/planner/PlannerController.java
  src/main/resources/templates/planner/EditForm.html
  src/main/resources/templates/planner/PlannerMain.html
  src/main/resources/templates/planner/SaveForm.html
Labels: 🎨 design

#133 Feature: 유저 정지 기간 설정
  src/main/java/com/example/algoyweb/AlgoyWebApplication.java
  src/main/java/com/example/algoyweb/model/dto/user/UserDto.java
  src/main/java/com/example/algoyweb/model/entity/user/User.java
  src/main/java/com/example/algoyweb/repository/user/UserRepository.java
  src/main/java/com/example/algoyweb/service/user/UserService.java
  src/main/resources/static/css/user/admin.css
Labels: 💪 enhancement, ✨ feature

#138 Feature: 관리자 페이지 버튼
  src/main/resources/static/css/fragments/header.css
  src/main/resources/templates/fragments/header.html
Labels: ✨ feature

#139 Design: 오답 노트 화면에 챗봇 프래그먼트 붙이기
  src/main/java/com/example/algoyweb/controller/WrongAnswerNote/WrongAnswerNoteThymeleafController.java
  src/main/resources/templates/wronganswernote/create-wrong-answer-note.html
  src/main/resources/templates/wronganswernote/edit-wrong-answer-note.html
  src/main/resources/templates/wronganswernote/list-wrong-answer-notes.html
  src/main/resources/templates/wronganswernote/view-wrong-answer-note.html
Labels: 🎨 design

#140 feat: Study
  src/main/java/com/example/algoyweb/controller/study/CommentController.java
  src/main/java/com/example/algoyweb/controller/study/StudyController.java
  src/main/java/com/example/algoyweb/exception/CustomException.java
  src/main/java/com/example/algoyweb/exception/GlobalExceptionHandler.java
  src/main/java/com/example/algoyweb/exception/errorcode/CommentErrorCode.java
  src/main/java/com/example/algoyweb/exception/errorcode/CommonErrorCode.java
  src/main/java/com/example/algoyweb/exception/errorcode/ErrorCode.java
  src/main/java/com/example/algoyweb/exception/errorcode/PlannerErrorCode.java
  src/main/java/com/example/algoyweb/exception/errorcode/StudyErrorCode.java
  src/main/java/com/example/algoyweb/exception/errorcode/UserErrorCode.java
  src/main/java/com/example/algoyweb/model/dto/comment/CommentDto.java
  src/main/java/com/example/algoyweb/model/dto/study/StudyDto.java
  src/main/java/com/example/algoyweb/model/entity/study/Comment.java
  src/main/java/com/example/algoyweb/model/entity/study/Participant.java
  src/main/java/com/example/algoyweb/model/entity/study/Study.java
  src/main/java/com/example/algoyweb/model/entity/user/User.java
  src/main/java/com/example/algoyweb/repository/study/CommentRepository.java
  src/main/java/com/example/algoyweb/repository/study/ParticipantRepository.java
  src/main/java/com/example/algoyweb/repository/study/StudyRepository.java
  src/main/java/com/example/algoyweb/repository/user/UserRepository.java
  src/main/java/com/example/algoyweb/service/planner/PlannerService.java
  src/main/java/com/example/algoyweb/service/study/CommentService.java
  src/main/java/com/example/algoyweb/service/study/StudyService.java
  src/main/java/com/example/algoyweb/service/user/UserService.java
  src/main/java/com/example/algoyweb/util/ConvertUtils.java
  src/test/java/com/example/algoyweb/service/planner/PlannerServiceTest.java
Labels: ✨ feature

#142 bug: 헤더 적용
  src/main/resources/static/css/fragments/modal.css
  src/main/resources/static/css/planner/PlannerEditForm.css
  src/main/resources/static/css/planner/PlannerMainCss.css
  src/main/resources/static/css/planner/PlannerSaveForm.css
  src/main/resources/static/css/study/StudyMainCss.css
  src/main/resources/static/js/planner/PlannerMainJs.js
  src/main/resources/templates/planner/EditForm.html
  src/main/resources/templates/planner/PlannerMain.html
  src/main/resources/templates/planner/SaveForm.html
  src/main/resources/templates/study/studymain.html
Labels: 🐞 bug, 🎨 design

#146 Feature: WebSocket 채팅방 서버 구현
  build.gradle
  src/main/java/com/example/algoyweb/config/SecurityConfig.java
  src/main/java/com/example/algoyweb/config/chatting/WebSocketConfig.java
  src/main/java/com/example/algoyweb/config/chatting/WebSocketSecurityConfig.java
  src/main/java/com/example/algoyweb/controller/chatting/ChattingController.java
  src/main/java/com/example/algoyweb/controller/chatting/ChattingWebSocketController.java
  src/main/java/com/example/algoyweb/exception/chatting/ChattingErrorCode.java
  src/main/java/com/example/algoyweb/exception/chatting/WebSocketExceptionHandler.java
  src/main/java/com/example/algoyweb/model/dto/chatting/ChattingDto.java
  src/main/java/com/example/algoyweb/model/dto/chatting/ChattingRoomDto.java
  src/main/java/com/example/algoyweb/model/dto/chatting/JoinRoomRequest.java
  src/main/java/com/example/algoyweb/model/dto/chatting/LeaveRoomRequest.java
  src/main/java/com/example/algoyweb/model/entity/chatting/Chatting.java
  src/main/java/com/example/algoyweb/model/entity/chatting/ChattingRoom.java
  src/main/java/com/example/algoyweb/repository/chatting/ChattingRepository.java
  src/main/java/com/example/algoyweb/repository/chatting/ChattingRoomRepository.java
  src/main/java/com/example/algoyweb/service/chatting/ChattingService.java
  src/main/java/com/example/algoyweb/util/chatting/ChattingConvertUtil.java
Labels: 👷‍♂️ chore, 💪 enhancement, ✨ feature

#148 Refactor: ban count 자료형 변경
  src/main/java/com/example/algoyweb/model/dto/user/UserDto.java
  src/main/java/com/example/algoyweb/model/entity/user/User.java
  src/main/java/com/example/algoyweb/service/user/UserService.java
Labels: ⚒️ refactor

#153 Feature: 회원정보수정에서 solvedAC username 수정하기
  src/main/java/com/example/algoyweb/controller/user/MyPageController.java
  src/main/java/com/example/algoyweb/controller/user/UserController.java
  src/main/java/com/example/algoyweb/model/entity/user/User.java
  src/main/java/com/example/algoyweb/service/user/UserService.java
  src/main/resources/static/js/mypage/userEdit.js
  src/main/resources/templates/mypage/userEdit.html
Labels: ✨ feature

#157 Feature: 유저 정지 개선
  src/main/java/com/example/algoyweb/controller/user/AdminController.java
  src/main/java/com/example/algoyweb/model/dto/auth/OAuthAttributes.java
  src/main/java/com/example/algoyweb/model/entity/auth/SessionUser.java
  src/main/java/com/example/algoyweb/model/entity/user/User.java
  src/main/java/com/example/algoyweb/service/auth/CustomOAuth2UserService.java
  src/main/java/com/example/algoyweb/service/user/UserPermissionService.java
  src/main/java/com/example/algoyweb/service/user/UserService.java
  src/main/resources/static/css/user/admin.css
  src/main/resources/static/js/user/admin.js
  src/main/resources/templates/user/admin.html
Labels: 💪 enhancement, ✨ feature, ⚒️ refactor

#159 Enhancement: 예외 처리 및 편의성을 위한 채팅 디자인
  src/main/java/com/example/algoyweb/controller/chatting/ChattingController.java
  src/main/java/com/example/algoyweb/controller/user/UserController.java
  src/main/java/com/example/algoyweb/exception/chatting/ChattingErrorCode.java
  src/main/java/com/example/algoyweb/model/entity/chatting/ChattingRoom.java
  src/main/java/com/example/algoyweb/repository/chatting/ChattingRoomRepository.java
  src/main/java/com/example/algoyweb/service/chatting/ChattingService.java
  src/main/java/com/example/algoyweb/service/user/UserService.java
  src/main/resources/static/css/chatting/chatting.css
  src/main/resources/static/js/chatting/chatting.js
  src/main/resources/templates/temp/chatting-demo.html
Labels: 🐞 bug, 🎨 design, 💪 enhancement

#160 Design: 채팅 클라이언트 디자인
  src/main/java/com/example/algoyweb/controller/chatting/ChattingController.java
  src/main/java/com/example/algoyweb/controller/chatting/ChattingWebSocketController.java
  src/main/java/com/example/algoyweb/exception/errorcode/ChattingErrorCode.java
  src/main/java/com/example/algoyweb/model/dto/chatting/ChattingRoomDto.java
  src/main/java/com/example/algoyweb/model/dto/chatting/JoinRoomResponse.java
  src/main/java/com/example/algoyweb/model/dto/chatting/LeaveRoomResponse.java
  src/main/java/com/example/algoyweb/model/entity/chatting/ChattingRoom.java
  src/main/java/com/example/algoyweb/service/chatting/ChattingService.java
  src/main/resources/static/css/fragments/chatting.css
  src/main/resources/static/js/chatting/chatting.js
  src/main/resources/static/js/fragments/chatting.js
  src/main/resources/templates/fragments/chatting.html
  src/main/resources/templates/temp/chatting-demo.html
Labels: 🎨 design, 💪 enhancement, ⚒️ refactor

#163 Refactor: 채팅 기능과 챗봇 기능 같은 페이지에서 쓸 수 있도록 조정
  src/main/resources/static/css/fragments/chatbot.css
  src/main/resources/static/css/fragments/chatting.css
  src/main/resources/static/js/fragments/chatbot.js
  src/main/resources/static/js/fragments/chatting.js
  src/main/resources/templates/fragments/chatbot.html
  src/main/resources/templates/fragments/chatting.html
  src/main/resources/templates/temp/chatbot-demo.html
Labels: ⚒️ refactor

#166 Feature: 구글 로그인 버튼 수정
  src/main/resources/static/css/user/login.css
  src/main/resources/templates/user/login.html
Labels: ✨ feature

#167 Feature/35 오답노트
  src/main/java/com/example/algoyweb/controller/WrongAnswerNote/CodeController.java
  src/main/java/com/example/algoyweb/controller/WrongAnswerNote/ImageController.java
  src/main/java/com/example/algoyweb/controller/WrongAnswerNote/WrongAnswerNoteRestController.java
  src/main/java/com/example/algoyweb/controller/WrongAnswerNote/WrongAnswerNoteThymeleafController.java
  src/main/java/com/example/algoyweb/model/dto/WrongAnswerNote/ImageDTO.java
  src/main/java/com/example/algoyweb/model/dto/WrongAnswerNote/WrongAnswerNoteDTO.java
  src/main/java/com/example/algoyweb/model/entity/WrongAnswerNote/Code.java
  src/main/java/com/example/algoyweb/model/entity/WrongAnswerNote/Image.java
  src/main/java/com/example/algoyweb/model/entity/WrongAnswerNote/WrongAnswerNote.java
  src/main/java/com/example/algoyweb/repository/WrongAnswerNote/CodeRepository.java
  src/main/java/com/example/algoyweb/repository/WrongAnswerNote/ImageRepository.java
  src/main/java/com/example/algoyweb/repository/WrongAnswerNote/WrongAnswerNoteRepository.java
  src/main/java/com/example/algoyweb/service/WrongAnswerNote/CodeService.java
  src/main/java/com/example/algoyweb/service/WrongAnswerNote/ImageService.java
  src/main/java/com/example/algoyweb/service/WrongAnswerNote/WrongAnswerNoteService.java
  src/main/java/com/example/algoyweb/util/WrongAnswerNote/ImageConvertUtil.java
  src/main/java/com/example/algoyweb/util/WrongAnswerNote/WrongAnswerNoteConvertUtil.java
  src/main/resources/static/css/wronganswernote/create-wrong-answer-note.css
  src/main/resources/static/css/wronganswernote/edit-wrong-answer-note.css
  src/main/resources/static/css/wronganswernote/list-wrong-answer-note.css
  src/main/resources/static/css/wronganswernote/view-wrong-answer-note.css
  src/main/resources/static/js/wronganswernote/create.js
  src/main/resources/static/js/wronganswernote/edit.js
  src/main/resources/static/js/wronganswernote/list.js
  src/main/resources/static/js/wronganswernote/view.js
  src/main/resources/templates/wronganswernote/create-wrong-answer-note.html
  src/main/resources/templates/wronganswernote/edit-wrong-answer-note.html
  src/main/resources/templates/wronganswernote/list-wrong-answer-notes.html
  src/main/resources/templates/wronganswernote/view-wrong-answer-note.html
Labels: 🎨 design, ✨ feature

#168 Enhancement: 5문제 받아오기
  src/main/java/com/example/algoyweb/config/SecurityConfig.java
  src/main/java/com/example/algoyweb/controller/user/UserAuthenticationSuccessHandler.java
  src/main/java/com/example/algoyweb/controller/user/UserController.java
  src/main/java/com/example/algoyweb/model/dto/allen/SolvedACJsonResponse.java
  src/main/java/com/example/algoyweb/model/dto/allen/SolvedACResponse.java
  src/main/java/com/example/algoyweb/model/entity/allen/SolvedACResponse.java
  src/main/java/com/example/algoyweb/model/entity/user/User.java
  src/main/java/com/example/algoyweb/repository/allen/SolvedACResponseRepository.java
  src/main/java/com/example/algoyweb/repository/user/UserRepository.java
  src/main/java/com/example/algoyweb/service/allen/AllenService.java
  src/main/java/com/example/algoyweb/util/ConvertUtils.java
  src/main/java/com/example/algoyweb/util/user/CustomAuthenticationSuccessHandler.java
Labels: 💪 enhancement

#172 Test: 채팅 기능 단위 테스트 코드 작성
  build.gradle
  src/main/java/com/example/algoyweb/controller/chatting/ChattingController.java
  src/main/java/com/example/algoyweb/exception/chatting/WebSocketExceptionHandler.java
  src/main/java/com/example/algoyweb/exception/errorcode/ChattingErrorCode.java
  src/main/java/com/example/algoyweb/model/dto/chatting/ErrorResponse.java
  src/main/java/com/example/algoyweb/model/entity/chatting/ChattingRoom.java
  src/main/java/com/example/algoyweb/service/chatting/ChattingService.java
  src/test/java/com/example/algoyweb/controller/chatting/ChattingControllerTest.java
  src/test/java/com/example/algoyweb/controller/chatting/ChattingWebSocketControllerTest.java
  src/test/java/com/example/algoyweb/repository/chatting/ChattingRepositoryTest.java
  src/test/java/com/example/algoyweb/repository/chatting/ChattingRoomRepositoryTest.java
  src/test/java/com/example/algoyweb/service/chatting/ChattingServiceTest.java
  src/test/resources/application.yml
Labels: 👷‍♂️ chore, 💪 enhancement, ⚒️ refactor, ✅ test

#176 bug: study
  src/main/resources/static/js/planner/EditFormJs.js
  src/main/resources/static/js/planner/SaveFormJs.js
Labels: 🐞 bug

#178 Refactor/177 로그인 cofig수정
  src/main/java/com/example/algoyweb/config/SecurityConfig.java
  src/main/java/com/example/algoyweb/util/user/UserAuthenticationSuccessHandler.java
  src/main/resources/templates/home.html
Labels: ⚒️ refactor

#179 Remove: 불필요 파일 삭제
  src/main/java/com/example/algoyweb/controller/user/UserAuthenticationSuccessHandler.java
Labels: ⚒️ refactor

#180 Remove: 불필요 파일 삭제
  src/main/java/com/example/algoyweb/util/user/CustomAuthenticationSuccessHandler.java
Labels: ⚒️ refactor

#181 Documentation: 채팅 기능에 Javadoc과 주석 달기
  src/main/java/com/example/algoyweb/config/chatting/WebSocketConfig.java
  src/main/java/com/example/algoyweb/controller/chatting/ChattingController.java
  src/main/java/com/example/algoyweb/controller/chatting/ChattingWebSocketController.java
  src/main/java/com/example/algoyweb/controller/temp/ChatBotViewController.java
  src/main/java/com/example/algoyweb/controller/temp/ChattingViewController.java
  src/main/java/com/example/algoyweb/exception/chatting/WebSocketExceptionHandler.java
  src/main/java/com/example/algoyweb/exception/errorcode/ChattingErrorCode.java
  src/main/java/com/example/algoyweb/model/dto/chatting/ChattingDto.java
  src/main/java/com/example/algoyweb/model/dto/chatting/ChattingRoomDto.java
  src/main/java/com/example/algoyweb/model/dto/chatting/CreateRoomRequest.java
  src/main/java/com/example/algoyweb/model/dto/chatting/ErrorResponse.java
  src/main/java/com/example/algoyweb/model/dto/chatting/InviteRequest.java
  src/main/java/com/example/algoyweb/model/dto/chatting/JoinRoomRequest.java
  src/main/java/com/example/algoyweb/model/dto/chatting/JoinRoomResponse.java
  src/main/java/com/example/algoyweb/model/dto/chatting/LeaveRoomRequest.java
  src/main/java/com/example/algoyweb/model/dto/chatting/LeaveRoomResponse.java
  src/main/java/com/example/algoyweb/model/dto/chatting/MessageRequest.java
  src/main/java/com/example/algoyweb/model/entity/chatting/Chatting.java
  src/main/java/com/example/algoyweb/model/entity/chatting/ChattingRoom.java
  src/main/java/com/example/algoyweb/repository/chatting/ChattingRepository.java
  src/main/java/com/example/algoyweb/repository/chatting/ChattingRoomRepository.java
  src/main/java/com/example/algoyweb/service/chatting/ChattingService.java
  src/main/java/com/example/algoyweb/util/chatting/ChattingConvertUtil.java
  src/main/resources/static/js/fragments/chatbot.js
  src/main/resources/static/js/fragments/chatting.js
  src/main/resources/templates/fragments/chatbot.html
  src/main/resources/templates/temp/chatting-demo.html
  src/test/java/com/example/algoyweb/controller/chatting/ChattingControllerTest.java
  src/test/java/com/example/algoyweb/controller/chatting/ChattingWebSocketControllerTest.java
  src/test/java/com/example/algoyweb/repository/chatting/ChattingRepositoryTest.java
  src/test/java/com/example/algoyweb/repository/chatting/ChattingRoomRepositoryTest.java
  src/test/java/com/example/algoyweb/service/chatting/ChattingServiceTest.java
Labels: 📚 documentation

#184 Design: 페이지에 챗봇, 채팅 붙이기
  src/main/java/com/example/algoyweb/controller/study/StudyController.java
  src/main/resources/templates/home.html
  src/main/resources/templates/planner/EditForm.html
  src/main/resources/templates/planner/PlannerMain.html
  src/main/resources/templates/planner/SaveForm.html
  src/main/resources/templates/study/StudyDetail.html
  src/main/resources/templates/study/StudyEdit.html
  src/main/resources/templates/study/StudyMain.html
  src/main/resources/templates/study/StudyNew.html
  src/main/resources/templates/wronganswernote/create-wrong-answer-note.html
  src/main/resources/templates/wronganswernote/edit-wrong-answer-note.html
  src/main/resources/templates/wronganswernote/list-wrong-answer-notes.html
  src/main/resources/templates/wronganswernote/view-wrong-answer-note.html
Labels: 🎨 design

#186 Test: 회원정보 수정 Test Code
  src/test/java/com/example/algoyweb/service/user/UserServiceTest.java
Labels: ✅ test

#188 Bug: 없는 사용자 초대에 대한 Alert 처리 및 에러 코드에 맞게 Alert 출력
  src/main/java/com/example/algoyweb/controller/chatting/ChattingController.java
  src/main/java/com/example/algoyweb/exception/errorcode/ChattingErrorCode.java
  src/main/java/com/example/algoyweb/service/chatting/ChattingService.java
  src/main/resources/static/js/fragments/chatting.js
  src/test/java/com/example/algoyweb/controller/chatting/ChattingControllerTest.java
  src/test/java/com/example/algoyweb/repository/chatting/ChattingRepositoryTest.java
Labels: 🐞 bug

#189 Enhancement: solvedAC 기반 문제추천 랜덤으로 받기
  src/main/java/com/example/algoyweb/controller/HomeController.java
  src/main/java/com/example/algoyweb/controller/user/UserController.java
  src/main/java/com/example/algoyweb/model/dto/allen/SolvedACResponseDto.java
  src/main/java/com/example/algoyweb/model/entity/allen/SolvedACResponseEntity.java
  src/main/java/com/example/algoyweb/model/entity/user/User.java
  src/main/java/com/example/algoyweb/repository/allen/SolvedACResponseRepository.java
  src/main/java/com/example/algoyweb/service/allen/AllenService.java
  src/main/java/com/example/algoyweb/service/user/UserService.java
  src/main/java/com/example/algoyweb/util/ConvertUtils.java
  src/main/resources/templates/home.html
Labels: 💪 enhancement

#191 Bug: 세션 스토리지를 이용하여 새로고침하거나 페이지를 이동해도 사용자 정보를 기억
  src/main/resources/static/js/fragments/chatting.js
Labels: 🐞 bug

#193 Test: 회원탈퇴 Test Code
  src/test/java/com/example/algoyweb/service/user/UserServiceTest.java
Labels: ✅ test

#197 Deploy: 서버 test
  src/main/resources/application.yml
Labels: :package: deploy

#198 Deploy: ci/cd 방식 변경
  .github/workflows/gradle.yml
Labels: :package: deploy

#199 Bug: OAuth2 오류
  src/main/java/com/example/algoyweb/config/SecurityConfig.java
  src/main/java/com/example/algoyweb/config/user/UserConfig.java
  src/main/java/com/example/algoyweb/controller/user/AdminController.java
  src/main/java/com/example/algoyweb/controller/user/UserController.java
  src/main/java/com/example/algoyweb/model/dto/auth/OAuthAttributes.java
  src/main/java/com/example/algoyweb/model/entity/auth/CustomOAuth2User.java
  src/main/java/com/example/algoyweb/service/auth/CustomOAuth2UserService.java
  src/main/java/com/example/algoyweb/service/user/UserPermissionService.java
  src/main/java/com/example/algoyweb/service/user/UserService.java
Labels: 🐞 bug

#200 Design/00 회원정보 수정
  src/main/resources/static/css/mypage/editUser.css
  src/main/resources/templates/mypage/userEdit.html
Labels: 🎨 design

#202 Design: 파비콘, 타이틀, footer
  src/main/resources/static/css/home/home.css
  src/main/resources/static/css/mypage/deleteUser.css
  src/main/resources/static/css/mypage/editUser.css
  src/main/resources/static/css/mypage/editUserCss.css
  src/main/resources/static/css/mypage/mypageCss.css
  src/main/resources/static/css/user/admin.css
  src/main/resources/static/css/user/login.css
  src/main/resources/static/css/wronganswernote/create-wrong-answer-note.css
  src/main/resources/static/css/wronganswernote/edit-wrong-answer-note.css
  src/main/resources/static/css/wronganswernote/list-wrong-answer-note.css
  src/main/resources/static/css/wronganswernote/view-wrong-answer-note.css
  src/main/resources/templates/DemoPage.html
  src/main/resources/templates/fragments/chatbot.html
  src/main/resources/templates/fragments/chatting.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/modal.html
  src/main/resources/templates/home.html
  src/main/resources/templates/mypage/userDelete.html
  src/main/resources/templates/mypage/userEdit.html
  src/main/resources/templates/mypage/userRestore.html
  src/main/resources/templates/password/find-password.html
  src/main/resources/templates/password/reset-password.html
  src/main/resources/templates/planner/EditForm.html
  src/main/resources/templates/planner/PlannerMain.html
  src/main/resources/templates/planner/SaveForm.html
  src/main/resources/templates/signup/signup.html
  src/main/resources/templates/study/StudyDetail.html
  src/main/resources/templates/study/StudyEdit.html
  src/main/resources/templates/study/StudyMain.html
  src/main/resources/templates/study/StudyNew.html
  src/main/resources/templates/temp/chatbot-demo.html
  src/main/resources/templates/temp/chatting-demo.html
  src/main/resources/templates/user/admin.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/wronganswernote/create-wrong-answer-note.html
  src/main/resources/templates/wronganswernote/edit-wrong-answer-note.html
  src/main/resources/templates/wronganswernote/list-wrong-answer-notes.html
  src/main/resources/templates/wronganswernote/view-wrong-answer-note.html
Labels: 🎨 design

#204 Deploy: 통합 배포
  .github/workflows/gradle.yml
Labels: :package: deploy

#206 feat: study
  src/main/resources/static/css/study/StudyDetailCss.css
  src/main/resources/static/js/study/StudyDetailJs.js
  src/main/resources/static/js/study/StudyMainJs.js
  src/main/resources/templates/study/StudyDetail.html
Labels: ✨ feature

#207 Bug : SCP가 1시간 이상 걸리는 이슈
  .github/workflows/gradle.yml
Labels: 🐞 bug

#209 Deploy: ec2 t3 배포 test
  .github/workflows/gradle.yml
Labels: :package: deploy

#213 Bug: 채팅 관련 버그 수정
  src/main/resources/static/css/fragments/chatbot.css
  src/main/resources/static/css/fragments/chatting.css
  src/main/resources/static/js/fragments/chatting.js
Labels: 🐞 bug

#215 Enhancement: 로그인이 안 되있을 경우 채팅 비활성화
  src/main/resources/templates/fragments/chatting.html
Labels: 💪 enhancement

#218 test: 통합 테스트
  src/main/java/com/example/algoyweb/controller/study/CommentController.java
  src/main/java/com/example/algoyweb/model/entity/study/Comment.java
  src/main/java/com/example/algoyweb/model/entity/user/User.java
  src/main/java/com/example/algoyweb/repository/study/ParticipantRepository.java
  src/main/java/com/example/algoyweb/repository/study/StudyRepository.java
  src/main/java/com/example/algoyweb/service/study/CommentService.java
  src/main/java/com/example/algoyweb/util/ConvertUtils.java
  src/main/java/com/example/algoyweb/util/user/CustomUserDetails.java
  src/test/java/com/example/algoyweb/IntegrationTest.java
Labels: ✅ test

#220 test: 통합테스트
  src/test/java/com/example/algoyweb/IntegrationTest.java
Labels: ✅ test

#223 Enhancement: 채닝 기능 보완
  src/main/java/com/example/algoyweb/controller/chatting/ChattingWebSocketController.java
  src/main/java/com/example/algoyweb/model/dto/chatting/JoinRoomResponse.java
  src/main/java/com/example/algoyweb/model/dto/chatting/LeaveRoomResponse.java
  src/main/java/com/example/algoyweb/model/entity/chatting/Chatting.java
  src/main/java/com/example/algoyweb/repository/chatting/ChattingRepository.java
  src/main/java/com/example/algoyweb/service/chatting/ChattingService.java
  src/main/java/com/example/algoyweb/util/chatting/ChattingConvertUtil.java
  src/main/resources/static/css/fragments/chatbot.css
  src/main/resources/static/css/fragments/chatting.css
  src/main/resources/static/js/fragments/chatting.js
  src/main/resources/templates/study/StudyEdit.html
  src/main/resources/templates/study/StudyNew.html
  src/test/java/com/example/algoyweb/IntegrationTest.java
  src/test/java/com/example/algoyweb/controller/chatting/ChattingControllerTest.java
  src/test/java/com/example/algoyweb/repository/chatting/ChattingRepositoryTest.java
  src/test/resources/application.yml
Labels: 🐞 bug, 🎨 design, 💪 enhancement

#224 Test: 통합 테스트 CI/CD에서 동작하도록 수정
  src/test/java/com/example/algoyweb/IntegrationTest.java
  src/test/java/com/example/algoyweb/repository/chatting/ChattingRepositoryTest.java
  src/test/java/com/example/algoyweb/repository/chatting/ChattingRoomRepositoryTest.java
  src/test/resources/application.yml
Labels: ✅ test

#226 Documentation: DB 초기화
  src/main/resources/application.yml
Labels: 📚 documentation

#227 Documentation: ddl-auto: none 설정
  src/main/resources/application.yml
Labels: 📚 documentation

#229 Design: 화면 수정 및 주석삭제
  src/main/resources/static/css/mypage/deleteUser.css
  src/main/resources/static/css/signup/signup.css
  src/main/resources/static/css/user/admin.css
  src/main/resources/static/css/user/login.css
  src/main/resources/static/js/planner/PlannerMainJs.js
  src/main/resources/templates/home.html
  src/main/resources/templates/planner/EditForm.html
  src/main/resources/templates/planner/PlannerMain.html
  src/main/resources/templates/planner/SaveForm.html
  src/main/resources/templates/signup/signup.html
  src/main/resources/templates/study/StudyEdit.html
  src/main/resources/templates/study/StudyMain.html
  src/main/resources/templates/study/StudyNew.html
  src/main/resources/templates/user/admin.html
  src/main/resources/templates/wronganswernote/create-wrong-answer-note.html
  src/main/resources/templates/wronganswernote/edit-wrong-answer-note.html
Labels: 🎨 design

#230 Docs: 리드미 작성
  README.md
  assets/img/architecture.png
  assets/img/erd.png
  assets/img/figma/account_recovery.png
  assets/img/figma/admin_page.png
  assets/img/figma/ban_reason.png
  assets/img/figma/find_pw1.png
  assets/img/figma/find_pw2.png
  assets/img/figma/home.png
  assets/img/figma/login.png
  assets/img/figma/login_google.png
  assets/img/figma/my_page.png
  assets/img/figma/planner_list.png
  assets/img/figma/planner_modal.png
  assets/img/figma/planner_update.png
  assets/img/figma/planner_write.png
  assets/img/figma/signup.png
  assets/img/figma/study_detail.png
  assets/img/figma/study_list.png
  assets/img/figma/study_update.png
  assets/img/figma/study_write.png
  assets/img/figma/user_delete.png
  assets/img/figma/user_edit.png
  assets/img/figma/wrong_answer_note_add_code.png
  assets/img/figma/wrong_answer_note_detail.png
  assets/img/figma/wrong_answer_note_list.png
  assets/img/figma/wrong_answer_note_update.png
  assets/img/figma/wrong_answer_note_write.png
  assets/img/profile/1.png
  assets/img/profile/2.png
  assets/img/profile/3.png
  assets/img/profile/4.png
  assets/img/profile/5.png
  assets/img/profile/6.png
  assets/img/troubleshooting/1.png
  assets/img/troubleshooting/2.png
  assets/img/troubleshooting/3.png
  assets/img/troubleshooting/4.png
  assets/img/troubleshooting/5.png
  assets/img/troubleshooting/6.png
  assets/img/troubleshooting/7.png
  src/main/java/com/example/algoyweb/config/SecurityConfig.java
Labels: 📚 documentation
