Repository high-five-ormi/Algoy-Web, pull requests merged in 2024-08, with the labels that each got.

#3 Docs: PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📚 documentation

#6 Feat: web 애플리케이션 gradle.yml 파일 업로드
  .github/workflows/gradle.yml
  .idea/.gitignore
Labels: ✨ feature

#8 feat: yml 파일 추가 및 배포 준비완료
  .github/workflows/gradle.yml
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ feature

#10 feat: 다시 배포하기
  .github/workflows/gradle.yml
Labels: 🐞 bug

#12 feat: 배포 test3
  .github/workflows/gradle.yml
Labels: 🐞 bug

#14 fea: 프로젝트 초기화 수정
  src/main/java/com/example/algoyweb/controller/DemoController.java
  src/main/java/com/example/algoyweb/domain/DemoEntity.java
  src/main/java/com/example/algoyweb/repository/DemoRepository.java
  src/main/java/com/example/algoyweb/service/DemoService.java
  src/main/resources/application.yml
Labels: 🐞 bug

#13 Bug: 배포test3
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/gradle.yml
  .gitignore
  .idea/.gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/algoyweb/AlgoyWebApplication.java
  src/main/resources/application.yml
  src/main/resources/static/DemoStyle.css
  src/main/resources/templates/DemoPage.html
  src/test/java/com/example/algoyweb/AlgoyWebApplicationTests.java
Labels: 🐞 bug

#19 Chore: Update gitignore
  .gitignore
Labels: 👷‍♂️ chore

#23 Feature: Planner
  src/main/java/com/example/algoyweb/controller/PlannerController.java
  src/main/java/com/example/algoyweb/domain/Planner.java
  src/main/java/com/example/algoyweb/dto/PlannerDto.java
  src/main/java/com/example/algoyweb/exception/PlannerErrorCode.java
  src/main/java/com/example/algoyweb/repository/PlannerRepository.java
  src/main/java/com/example/algoyweb/service/PlannerService.java
  src/main/java/com/example/algoyweb/utils/ConvertUtils.java
  src/main/resources/static/css/PlannerMainCss.css
  src/main/resources/templates/planner/PlannerMain.html
  src/main/resources/templates/planner/SaveForm.html
Labels: ✨ feature

#27 Feat: Nginx 8081 접속 test
  src/main/java/com/example/algoyweb/controller/PlannerController.java
Labels: 🐞 bug

#28 Feat: Nginx 8081 접속
  src/main/java/com/example/algoyweb/controller/PlannerController.java
Labels: 🐞 bug

#29 Feat: Nginx로 8081 접속하기
  src/main/java/com/example/algoyweb/controller/PlannerController.java
Labels: 🐞 bug

#30 Feat: Nginx 마지막 test
  src/main/java/com/example/algoyweb/controller/PlannerController.java
Labels: 🐞 bug

#33 Design: 플래너 메인 페이지 PR
  src/main/java/com/example/algoyweb/controller/planner/PlannerController.java
  src/main/java/com/example/algoyweb/model/dto/planner/PlannerDto.java
  src/main/java/com/example/algoyweb/model/entity/planner/Planner.java
  src/main/java/com/example/algoyweb/model/entity/user/User.java
  src/main/java/com/example/algoyweb/repository/planner/PlannerRepository.java
  src/main/java/com/example/algoyweb/service/planner/PlannerService.java
  src/main/java/com/example/algoyweb/util/ConvertUtils.java
  src/main/resources/static/css/PlannerMainCss.css
  src/main/resources/static/css/planner/PlannerMainCss.css
  src/main/resources/static/css/planner/PlannerSaveForm.css
  src/main/resources/static/img/algoy-1.png
  src/main/resources/static/img/planner-icon.png
  src/main/resources/static/img/search-glasses.png
  src/main/resources/static/img/user-icon.png
  src/main/resources/templates/planner/PlannerMain.html
  src/main/resources/templates/planner/SaveForm.html
Labels: 🎨 design, ⚒️ refactor

#34 Feat: 회원가입
  src/main/java/com/example/algoyweb/config/SecurityConfig.java
  src/main/java/com/example/algoyweb/config/user/UserConfig.java
  src/main/java/com/example/algoyweb/controller/user/UserController.java
  src/main/java/com/example/algoyweb/service/user/UserService.java
  src/main/resources/static/DemoStyle.css
  src/main/resources/static/js/signup/signup.js
  src/main/resources/templates/login.html
  src/main/resources/templates/signup/signup.html
Labels: 🎨 design, ✨ feature, ⚒️ refactor

#36 Feat: 오답노트
  src/main/java/com/example/algoyweb/controller/WrongAnswerNote/WrongAnswerNoteController.java
  src/main/java/com/example/algoyweb/model/dto/WrongAnswerNote/WrongAnswerNoteDTO.java
  src/main/java/com/example/algoyweb/model/entity/WrongAnswerNote/WrongAnswerNote.java
  src/main/java/com/example/algoyweb/repository/WrongAnswerNote/WrongAnswerNoteRepository.java
  src/main/java/com/example/algoyweb/service/WrongAnswerNote/WrongAnswerNoteService.java
  src/main/java/com/example/algoyweb/util/WrongAnswerNote/WrongAnswerNoteConvertUtil.java
Labels: ✨ feature

#39 Refactor : 로그인+회원가입 구현 완료
  src/main/java/com/example/algoyweb/config/SecurityConfig.java
  src/main/java/com/example/algoyweb/controller/HomeController.java
  src/main/java/com/example/algoyweb/controller/user/UserController.java
  src/main/java/com/example/algoyweb/model/dto/user/UserDto.java
  src/main/java/com/example/algoyweb/model/entity/user/Role.java
  src/main/java/com/example/algoyweb/model/entity/user/User.java
  src/main/java/com/example/algoyweb/service/user/UserDetailsService.java
  src/main/java/com/example/algoyweb/service/user/UserService.java
  src/main/resources/static/css/HomeCss.css
  src/main/resources/static/css/user/login.css
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
  src/main/resources/templates/signup/signup.html
  src/main/resources/templates/user/login.html
Labels: 🎨 design, ⚒️ refactor

#40 Feat: 구글 소셜 로그인
  build.gradle
  src/main/java/com/example/algoyweb/config/SecurityConfig.java
  src/main/java/com/example/algoyweb/config/auth/CustomOAuth2UserService.java
  src/main/java/com/example/algoyweb/controller/user/UserController.java
  src/main/java/com/example/algoyweb/model/dto/auth/OAuthAttributes.java
  src/main/java/com/example/algoyweb/model/dto/auth/SessionUser.java
  src/main/java/com/example/algoyweb/model/dto/user/UserDto.java
  src/main/java/com/example/algoyweb/model/entity/user/Role.java
  src/main/java/com/example/algoyweb/model/entity/user/User.java
  src/main/java/com/example/algoyweb/service/user/UserDetailsService.java
  src/main/java/com/example/algoyweb/service/user/UserService.java
  src/main/resources/static/css/user/login.css
  src/main/resources/templates/signup/signup.html
  src/main/resources/templates/user/login.html
Labels: ✨ feature

#42 Test: Test comment 추가
  src/main/java/com/example/algoyweb/controller/user/UserController.java
Labels: ✅ test

#46 Chore: 구글 로그인 환경 변수 추가
  .github/workflows/gradle.yml
  src/main/resources/application.yml
Labels: 👷‍♂️ chore

#50 Refactor: yml update로 수정
  src/main/resources/application.yml
Labels: ⚒️ refactor, :package: deploy

#51 Documentation: yml파일 테이블 생성 후 다시 ddl-auto: none 설정
  src/main/resources/application.yml
Labels: 📚 documentation

#54 Refactor: 코드 리펙토링
  src/main/java/com/example/algoyweb/config/SecurityConfig.java
  src/main/java/com/example/algoyweb/controller/user/UserController.java
  src/main/java/com/example/algoyweb/model/dto/user/UserDto.java
  src/main/java/com/example/algoyweb/model/entity/auth/SessionUser.java
  src/main/java/com/example/algoyweb/model/entity/user/User.java
  src/main/java/com/example/algoyweb/service/auth/CustomOAuth2UserService.java
  src/main/java/com/example/algoyweb/service/user/UserService.java
  src/main/resources/static/js/signup/signup.js
  src/main/resources/templates/signup/signup.html
Labels: ⚒️ refactor
